FROM python:3.7-alpine

RUN apk update && \
    apk add --no-cache bash && \
    apk add --update build-base python3-dev py-pip && \
    rm -rf /var/cache/apk/*

ENV LIBRARY_PATH=/lib:/usr/lib

WORKDIR /app

COPY . /app/

RUN pip install --no-cache-dir slack_bolt requests

CMD ["python", "slack.py"]